### ISSUE TITLE
Interpretability

### ISSUE THREAD

**Issue by antranttu** [jambo6/generalised-signature-method#1]
Hello, 

First of all, thank you for the great work! I really learned a lot from your paper on the generalized signature method. I do have one question I hope you can shed on light on.

The paper mentions one of the benefits of the signature method when applied to time series data is that it extracts an interpretable feature set. So my question is: in terms of what are the features interpretable? Does the method return some sort of feature importance? Can we actually plot the signature path of a channel to discriminate a positive from a negative instance?

Thank you!

**Comment by jambo6** [comment]
Hi,

Thanks for the interest and kind comments!

The interpretability is to do with the difference between using user extracted features compared with learnt features. If we learn features from the time series (e.g. RNN), then we can try and get some interpretability on the raw input features using say SHAP/LIME, but its difficult to do much else. If we use user extracted features on the other hand, then learn on these, we can get interpretability with respect to all the input features, giving us more information. 

Additional interpretability can be achieved as far as the signature features themselves are interpretable. For example, the S^{i, j} term describes some information about the interaction between features i, j, and has a physical meaning as can be seen from Figure 1 in the paper. If we learn an algorithm on such signatures, we can (in theory) gain interpretability on which feature interactions are the most important. This is true of any non-learnt features. Additional interpretability can be understood as far as we understand those features, which is basically the point we are making with signatures. 

How you might use this in practice is take the signature to depth^N and run some classifier on the data. You can then use SHAP, or just use a linear classifier, to get importances of the base features + the signature features. Looking for example on the depth 2 terms can give you an indication of what interactions are also important. As depth get larger there becomes more obscurity, but this is the basic idea. 

Signatures also come equipped with the universal nonlinearity theorem, which means given infinite labelled data and compute, we can learn the optimal mapping function using linear regression on the signature. In this case, the method is fully interpretable with respect to the signature coefficients. However, from my experience this is more theoretical than actually useful in practice.
